export const siteConfig = {
  name: "DK Creative Solutions",
  shortName: "DK Creative",
  tagline: "Transforming Ideas Into Digital Experiences",
  description:
    "DK Creative Solutions is a freelance creative technology studio specializing in website development, UI/UX design, video editing, and poster design. We build premium digital experiences for ambitious brands.",
  url: "https://www.dkcreativesolutions.com",
  ogImage: "/og-image.png",
  email: "hello@dkcreativesolutions.com",
  phone: "+91 9972879256",
  phoneRaw: "+919972879256",
  location: "India (Remote / Worldwide)",
  founder: "DK",
  keywords: [
    "DK Creative Solutions",
    "DK Creative Solution",
    "DK Creative",
    "Deepakkumar",
    "Deepakkumar V",
    "Deepak",
    "Deepak Developer",
    "Deepak Web Developer",
    "Deepak Full Stack Developer",
    "Freelance Web Developer",
    "Freelance Developer India",
    "Website Developer",
    "Website Designer",
    "Website Development",
    "Professional Website Development",
    "Custom Website Development",
    "Responsive Website Design",
    "Business Website",
    "Portfolio Website",
    "Landing Page Development",
    "React Developer",
    "React JS Developer",
    "Frontend Developer",
    "Backend Developer",
    "Node.js Developer",
    "Express.js Developer",
    "MERN Stack Developer",
    "Firebase Developer",
    "Flutter Developer",
    "FlutterFlow Developer",
    "JavaScript Developer",
    "HTML CSS Developer",
    "UI UX Designer",
    "Graphic Designer",
    "Logo Designer",
    "Poster Designer",
    "Video Editor",
    "YouTube Thumbnail Designer",
    "YouTube Video Editor",
    "Digital Marketing",
    "SEO Expert",
    "SEO Services",
    "Technical SEO",
    "On Page SEO",
    "Off Page SEO",
    "Local SEO",
    "Search Engine Optimization",
    "Google SEO",
    "Website Optimization",
    "Website Speed Optimization",
    "Social Media Marketing",
    "Brand Identity Design",
    "Creative Agency",
    "Web Application Development",
    "Mobile App Development",
    "Software Development",
    "Website Maintenance",
    "Website Hosting",
    "Website Security",
    "Web Developer Tamil Nadu",
    "Website Developer Tamil Nadu",
    "Website Designer Tamil Nadu",
    "Website Developer India",
    "Digital Marketing Tamil Nadu",
    "SEO Services Tamil Nadu",
    "Freelance Web Developer Tamil Nadu",
    "Affordable Website Development India",
    "Best Web Development Company India",
    "Website Design",
    "Website Redesign",
    "Corporate Website",
    "Landing Page",
    "E-commerce Website",
    "Custom Web Application",
    "React Website",
    "Node.js Backend",
    "Firebase Integration",
    "Admin Dashboard",
    "CMS Development",
    "SEO Optimization",
    "Google Search Console Setup",
    "Performance Optimization",
    "Responsive Design",
    "Modern UI Design",
    "UI/UX Design",
    "Video Editing",
    "Motion Graphics",
    "Poster Design",
    "Social Media Creatives",
    "Branding"
  ],
  links: {
    // github: "https://github.com/dk-creative-solutions",
    // linkedin: "https://www.linkedin.com/in/dk-creative-solutions",
    instagram: "https://www.instagram.com/dpak.dev_/",
    // twitter: "https://twitter.com/dkcreativesoln",
    youtube: "https://www.youtube.com/@dkcreativesolutions",
    // behance: "https://www.behance.net/dkcreativesolutions",
    whatsapp: "https://wa.me/919972879256",
  },
};

export const NAV_LINKS = [
  { label: "Home", href: "#home" },
  { label: "Services", href: "#services" },
  { label: "Projects", href: "#projects" },
  { label: "Video Editing", href: "#video-editing" },
  { label: "Posters", href: "#posters" },
  { label: "Process", href: "#process" },
  { label: "Testimonials", href: "#testimonials" },
  { label: "Contact", href: "#contact" },
] as const;

export const SERVICE_OPTIONS = [
  "Website Development",
  "Video Editing",
  "Poster Design",
  "UI/UX Design",
  "Landing Page Development",
  "Portfolio Website Development",
  "Other",
] as const;
